const booking=document.querySelector('#booking');
document.querySelectorAll('[data-book]').forEach(b=>b.addEventListener('click',()=>booking.showModal()));
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('[data-close]').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()})});
const photos=[["rodjendan-dekoracija.webp", "Rođendanska dekoracija s balonima"], ["rodjendan-bazen.webp", "Proslava osamnaestog rođendana pored bazena"], ["svadba-mladenci.jpg", "Mladenci pored bazena"], ["svadba-resort.jpg", "Svadbeni dan ispred resorta"], ["svadba-dobrodoslica.jpg", "Dekorisan ulaz za svadbu"], ["svadba-terasa.jpg", "Terasa pripremljena za slavlje"], ["svadba-sto.jpg", "Svečano uređen sto"], ["svadba-dekoracija.jpg", "Cvjetna svadbena dekoracija"], ["svadba-proslava.jpg", "Svadbena proslava pod svjetlima"], ["bazen-vrt.jpg", "Bazen i vrt iz zraka"],['690832512','Pogled iz zraka na cijeli Rakovica Resort'],['886473639','Bazen i ležaljke pod ljetnim suncem'],['886469086','Dnevni boravak i trpezarija'],['886471565','Prostor restorana'],['886473652','Zeleni vrt resorta'],['886473780','Sjenica i bazen iz zraka'],['886473440','Natkrivena terasa za odmor'],['886469368','Ugodan dnevni boravak'],['886472886','Kuhinja u smještaju'],['886469306','Drveni enterijer i prostor za sjedenje'],['886473233','Odmor na ležaljkama pored bazena'],['886473649','Bazen, suncobrani i zelenilo'],['886473284','Ljetni pogled na bazen'],['690832979','Resort okružen prirodom'],['690836179','Uređeni prilaz resortu'],['690836172','Druženje u sjenici'],['858683018','Večernja atmosfera u resortu'],['705624269','Bazen uz smještajne objekte'],['690836092','Pogled na prostor oko bazena'],['690836147','Pogled iz zraka na smještaj'],['690836149','Resort i vrt'],['886469206','Kutak dnevnog boravka'],['886469077','Detalji enterijera'],['886472919','Restoran i prostor za druženje'],['886471820','Šareni enterijer restorana'],['886472453','Prostrani dnevni boravak'],['886473429','Drvena sjenica u zelenilu'],['886473672','Ulaz dobrodošlice u resort'],['886473721','Vrt i prilaz bazenu']];
const gallery=document.querySelector('#gallery'),lightbox=document.querySelector('#lightbox'),large=document.querySelector('#large-photo');let current=0;
function displayPhoto(i){current=(i+photos.length)%photos.length;large.src='assets/'+(photos[current][0].includes('.')?photos[current][0]:photos[current][0]+'.jpg');large.alt=photos[current][1];document.querySelector('#photo-count').textContent=(current+1)+' / '+photos.length+' · '+photos[current][1]}
photos.forEach(([file,alt],i)=>{const b=document.createElement('button');b.hidden=i>=7;b.setAttribute('aria-label','Otvori fotografiju: '+alt);const img=document.createElement('img');img.src='assets/'+(file.includes('.')?file:file+'.jpg');img.alt=alt;img.loading='lazy';b.append(img);b.addEventListener('click',()=>{displayPhoto(i);lightbox.showModal()});gallery.append(b)});
document.querySelector('#more-photos').addEventListener('click',function(){const expanded=this.getAttribute('aria-expanded')==='true';Array.from(gallery.children).forEach((b,i)=>b.hidden=!expanded?false:i>=7);this.setAttribute('aria-expanded',String(!expanded));this.textContent=expanded?'Pogledajte sve fotografije +':'Prikažite manje −';if(expanded)document.querySelector('#galerija').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})});
document.querySelector('.gallery-prev').addEventListener('click',()=>displayPhoto(current-1));document.querySelector('.gallery-next').addEventListener('click',()=>displayPhoto(current+1));lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();displayPhoto(current-1)}if(e.key==='ArrowRight'){e.preventDefault();displayPhoto(current+1)}});document.querySelector('#year').textContent=new Date().getFullYear();
